[versions]
agp = "8.6.1"
credentials = "<latest version>"
firebaseBom = "33.6.0"
firebaseBomVersion = "33.6.0"
glide = "4.16.0"
googleid = "<latest version>"
gotrue = "0.5.0"
gotrueKtx = "<latest_version>"
kotlin = "1.9.24"
coreKtx = "1.13.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
navigationFragmentKtx = "2.8.4"
navigationUiKtx = "2.8.4"
parcelize = "3.1.2"
playServicesAuth = "21.2.0"
roomCompiler = "2.6.1"
runtimeAndroid = "1.7.5"
firebaseAuthCommon = "9.8.0"
firebaseAuthKtx = "23.1.0"
firebaseAuth = "23.1.0"
googleGmsGoogleServices = "4.4.2"
firebaseDatabase = "21.0.0"
firebaseFirestoreKtx = "25.1.1"
storageKtx = "<latest_version>"
firebaseStorageKtx = "21.0.1"
roomCommon = "2.6.1"
roomKtx = "2.6.1"
swiperefreshlayout = "1.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-bom-v3102 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
gotrue = { module = "io.github.jshcrowthe.supabase-kt:gotrue", version.ref = "gotrue" }
gotrue-ktx = { module = "io.supabase:gotrue-ktx", version.ref = "gotrueKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
firebase-auth-common = { group = "com.google.firebase", name = "firebase-auth-common", version.ref = "firebaseAuthCommon" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
parcelize = { module = "parcelize:parcelize", version.ref = "parcelize" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
storage-ktx = { module = "io.supabase:storage-ktx", version.ref = "storageKtx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

